/**
 * Ülke Kod Eşleştirmeleri - ATLAS İnteraktif
 * GeoJSON ülke adları -> ISO Alpha-2 kodları
 */

export const COUNTRY_ISO_MAP = {
    // Özel durumlar
    'United States of America': 'us',
    'United Kingdom': 'gb',
    'Turkey': 'tr',
    'Türkiye': 'tr',
    'South Korea': 'kr',
    'North Korea': 'kp',
    'Russia': 'ru',
    'China': 'cn',
    'Japan': 'jp',
    'India': 'in',
    'Germany': 'de',
    'France': 'fr',
    'Brazil': 'br',
    'Canada': 'ca',
    'Australia': 'au',
    'Mexico': 'mx',
    'Spain': 'es',
    'Italy': 'it',
    'Netherlands': 'nl',
    'Belgium': 'be',
    'Switzerland': 'ch',
    'Sweden': 'se',
    'Norway': 'no',
    'Denmark': 'dk',
    'Finland': 'fi',
    'Poland': 'pl',
    'Czech Republic': 'cz',
    'Czechia': 'cz',
    'Austria': 'at',
    'Greece': 'gr',
    'Portugal': 'pt',
    'Ireland': 'ie',
    'New Zealand': 'nz',
    'South Africa': 'za',
    'Egypt': 'eg',
    'Nigeria': 'ng',
    'Kenya': 'ke',
    'Ethiopia': 'et',
    'Argentina': 'ar',
    'Chile': 'cl',
    'Colombia': 'co',
    'Peru': 'pe',
    'Venezuela': 've',
    'Saudi Arabia': 'sa',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Israel': 'il',
    'Pakistan': 'pk',
    'Bangladesh': 'bd',
    'Vietnam': 'vn',
    'Thailand': 'th',
    'Philippines': 'ph',
    'Malaysia': 'my',
    'Singapore': 'sg',
    'Indonesia': 'id',
    'Ukraine': 'ua',
    'Romania': 'ro',
    'Hungary': 'hu',
    'Bulgaria': 'bg',
    'Serbia': 'rs',
    'Croatia': 'hr',
    'Slovenia': 'si',
    'Slovakia': 'sk',
    'Lithuania': 'lt',
    'Latvia': 'lv',
    'Estonia': 'ee',

    // Orta Asya ve Kafkasya
    'Kazakhstan': 'kz',
    'Uzbekistan': 'uz',
    'Turkmenistan': 'tm',
    'Kyrgyzstan': 'kg',
    'Tajikistan': 'tj',
    'Armenia': 'am',
    'Azerbaijan': 'az',
    'Georgia': 'ge',
    'Mongolia': 'mn',
    'Afghanistan': 'af',

    // Afrika
    'Algeria': 'dz',
    'Angola': 'ao',
    'Benin': 'bj',
    'Botswana': 'bw',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cameroon': 'cm',
    'Cape Verde': 'cv',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Comoros': 'km',
    'Congo': 'cg',
    'Democratic Republic of the Congo': 'cd',
    'Djibouti': 'dj',
    'Equatorial Guinea': 'gq',
    'Eritrea': 'er',
    'Gabon': 'ga',
    'Gambia': 'gm',
    'Ghana': 'gh',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Ivory Coast': 'ci',
    "Côte d'Ivoire": 'ci',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Mali': 'ml',
    'Mauritania': 'mr',
    'Mauritius': 'mu',
    'Morocco': 'ma',
    'Mozambique': 'mz',
    'Namibia': 'na',
    'Niger': 'ne',
    'Rwanda': 'rw',
    'Sao Tome and Principe': 'st',
    'Senegal': 'sn',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Somalia': 'so',
    'South Sudan': 'ss',
    'Sudan': 'sd',
    'Swaziland': 'sz',
    'Eswatini': 'sz',
    'Tanzania': 'tz',
    'Togo': 'tg',
    'Tunisia': 'tn',
    'Uganda': 'ug',
    'Zambia': 'zm',
    'Zimbabwe': 'zw',

    // Güney Amerika
    'Bolivia': 'bo',
    'Ecuador': 'ec',
    'Guyana': 'gy',
    'Paraguay': 'py',
    'Suriname': 'sr',
    'Uruguay': 'uy',
    'French Guiana': 'gf',

    // Orta Amerika ve Karayipler
    'Belize': 'bz',
    'Costa Rica': 'cr',
    'El Salvador': 'sv',
    'Guatemala': 'gt',
    'Honduras': 'hn',
    'Nicaragua': 'ni',
    'Panama': 'pa',
    'Cuba': 'cu',
    'Dominican Republic': 'do',
    'Haiti': 'ht',
    'Jamaica': 'jm',
    'Trinidad and Tobago': 'tt',
    'Bahamas': 'bs',
    'Barbados': 'bb',
    'Grenada': 'gd',
    'Saint Lucia': 'lc',
    'Saint Vincent and the Grenadines': 'vc',
    'Antigua and Barbuda': 'ag',
    'Dominica': 'dm',
    'Saint Kitts and Nevis': 'kn',

    // Orta Doğu
    'Jordan': 'jo',
    'Kuwait': 'kw',
    'Lebanon': 'lb',
    'Oman': 'om',
    'Qatar': 'qa',
    'Syria': 'sy',
    'United Arab Emirates': 'ae',
    'Yemen': 'ye',
    'Bahrain': 'bh',
    'Palestine': 'ps',

    // Asya-Pasifik
    'Myanmar': 'mm',
    'Burma': 'mm',
    'Cambodia': 'kh',
    'Laos': 'la',
    'Nepal': 'np',
    'Bhutan': 'bt',
    'Sri Lanka': 'lk',
    'Maldives': 'mv',
    'Brunei': 'bn',
    'East Timor': 'tl',
    'Timor-Leste': 'tl',
    'Papua New Guinea': 'pg',
    'Fiji': 'fj',
    'Solomon Islands': 'sb',
    'Vanuatu': 'vu',
    'Samoa': 'ws',
    'Tonga': 'to',
    'Micronesia': 'fm',
    'Palau': 'pw',
    'Marshall Islands': 'mh',
    'Kiribati': 'ki',
    'Nauru': 'nr',
    'Tuvalu': 'tv',

    // Avrupa (Ek)
    'Albania': 'al',
    'Bosnia and Herzegovina': 'ba',
    'Cyprus': 'cy',
    'Iceland': 'is',
    'Luxembourg': 'lu',
    'Malta': 'mt',
    'Moldova': 'md',
    'Montenegro': 'me',
    'North Macedonia': 'mk',
    'Macedonia': 'mk',
    'Belarus': 'by',
    'Andorra': 'ad',
    'Monaco': 'mc',
    'Liechtenstein': 'li',
    'San Marino': 'sm',
    'Vatican': 'va',
    'Kosovo': 'xk'
};

/**
 * Ülke adından ISO Alpha-2 kodu döndürür
 */
export function getCountryISOCode(countryName, isoA2FromGeoJSON) {
    // Önce GeoJSON'dan gelen kodu dene
    if (isoA2FromGeoJSON && isoA2FromGeoJSON !== '-99' && isoA2FromGeoJSON !== 'XX') {
        return isoA2FromGeoJSON.toLowerCase();
    }
    
    // Manuel mapping'den bul
    if (COUNTRY_ISO_MAP[countryName]) {
        return COUNTRY_ISO_MAP[countryName];
    }
    
    // Bulamazsa varsayılan
    console.warn(`ISO kodu bulunamadı: ${countryName}`);
    return null;
}

